# Generated by Django 2.1.4 on 2021-05-03 12:42

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('narrator', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_in_sec', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.BooleanField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_audiobook',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_in_sec', models.IntegerField(blank=True, default=0, null=True)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('participants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=10)),
                ('status', models.BooleanField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_podcast',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_in_sec', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.BooleanField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('module_step_settings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_songs',
            },
        ),
    ]
