# Generated by Django 2.1.4 on 2021-05-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='module_step_settings',
        ),
    ]
